language: rust
rust:
- stable
- beta
- nightly

matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true

cache: cargo

before_script:
- rustup target add i686-unknown-linux-gnu

script:
- cargo test --verbose --target i686-unknown-linux-gnu